---
title: "Emotion Analysis"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

# Load Data
```{r load data}
require(tidytext)
require(janeaustenr)
require(dplyr)
require(stringr)
require(stringi)
require(tidyr)
require(ggplot2)
require(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)

twitter <- read.csv("Twitter情感分析数据.csv", 
                    header = TRUE, stringsAsFactors = FALSE) %>%
  mutate(date = as.Date(date, "%d/%m/%Y"))

stock <- read.csv("股票数据.csv", 
                  header = TRUE, stringsAsFactors = FALSE) %>%
  rename(date = Date) %>%
  mutate(date = as.Date(date, "%Y-%m-%d")) %>%
  mutate(Close.log = log(Close))

plot.theme <- theme(
  legend.position = "bottom",
  axis.text.x=element_text(size=12),
  axis.text.y=element_text(size=12),
  axis.title.x=element_text(size=14),
  axis.title.y=element_text(size=14),
  axis.title = element_text(size=16, vjust=3),
  plot.title = element_text(hjust = 0.5)
)

ggplot(stock, aes(date, Close)) +
           geom_line(na.rm=TRUE) + 
           geom_point() +
           ggtitle("Stock Price") +
           xlab("Date") + ylab("Close Price") +
           # scale_x_date(labels=format ("%d %m")) +
           theme(plot.title = element_text(lineheight=.8, face="bold", 
                                          size = 20)) +
  plot.theme 

```

# Emotion Analysis
```{r}

knitr::kable(head(get_sentiments("bing")), caption = "The Words of Sentiment")

twitter.day <- twitter %>%
  # mutate(tweet = stri_match_all_regex(tweet, '[[:alpha:]]')) %>%
  select(date, tweet) %>%
  group_by(date) %>%
  summarise (tweet = paste0(tweet, collapse = " ")) %>%
  unnest_tokens(word, tweet)

bing_word_counts <- twitter.day %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

bing_word_counts %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") + 
  labs(y = "Contribution to sentiment",x = NULL) + 
  coord_flip()

library(wordcloud2)
colorVec = rep(c('red', 'skyblue'), length.out=nrow(demoFreq))
twitter.day %>% 
  inner_join(get_sentiments("bing")) %>%
  count(word) %>%
  rename(freq = n) %>%
  filter(freq >= 5) %>%
  data.frame %>%
  wordcloud2(size = 2, minRotation = -pi/6, maxRotation = pi/6,
             color = colorVec)

afinn <- twitter.day %>%
  inner_join(get_sentiments("afinn")) %>%
  group_by(date) %>%
  summarise(sentiment = sum(score)) %>%
  mutate(method = "AFINN")

bing <- twitter.day %>%
  inner_join(get_sentiments("bing")) %>%
  mutate(method = "Bing et al.") %>%
  count(date, method, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

nrc <- twitter.day %>%
  inner_join(get_sentiments("nrc")) %>%
  mutate(method = "NRC") %>%
  count(date, method, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

bind_rows(afinn, bing, nrc) %>%
  ggplot(aes(date, sentiment, fill = method)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~method, ncol = 1, scales = "free_y")

```

## Model Prediction
```{r}
stock.twitter <- stock %>%
  inner_join(afinn %>% ungroup %>% select(date, sentiment) %>%
               rename(sentiment_afinn = sentiment), by = "date") %>%
    inner_join(bing %>% ungroup %>% select(date, sentiment) %>%
               rename(sentiment_bing = sentiment), by = "date") %>%
    inner_join(nrc %>% ungroup %>% select(date, sentiment) %>%
               rename(sentiment_nrc = sentiment), by = "date")
  
Model_baseline <- lm(Close ~ Open, data = stock.twitter)
summary(Model_baseline)

Model_LR <- lm(Close ~ Open  + sentiment_nrc + sentiment_bing + sentiment_afinn, data = stock.twitter)
summary(Model_LR)
Model_LR.predict <- cbind.data.frame(date = stock.twitter$date, Close = predict(Model_LR))




# grow tree
Model_TR <- rpart(Close ~ Open + sentiment_nrc + sentiment_bing + sentiment_afinn,
             method="anova", data=stock.twitter)

# plotcp(Model_TR) # visualize cross-validation results 
# Model_TR <- prune(Model_TR, cp=0.041) # from cptable
fancyRpartPlot(Model_TR)

Model_TR.predict <- cbind.data.frame(date = stock.twitter$date, Close = predict(Model_TR))

bind_rows(stock.twitter %>% select(date, Close) %>% mutate(method = "Raw"),
          Model_LR.predict %>% mutate(method = "Linear"),
          Model_TR.predict %>% mutate(method = "Tree")
          ) %>%
  ggplot(aes(date, Close, color=method)) +
           geom_line(na.rm=TRUE) + 
           geom_point() +
           ggtitle("Stock Price") +
           xlab("Date") + ylab("Close Price") +
           # scale_x_date(labels=format ("%d %m")) +
           theme(plot.title = element_text(lineheight=.8, face="bold", 
                                          size = 20)) +
  plot.theme 

```

